apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: student-api-route
  namespace: student-api
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`one2n.shubhamxshah.xyz`)
      kind: Rule
      services:
        - name: student-service
          port: 3002
      middlewares:
        - name: default-headers
  # tls:
  #   secretName: local-shubhamxshah-live-staging-tls
