apiVersion: v1
data:
  alertmanager.yml: YXBpVmVyc2lvbjogbW9uaXRvcmluZy5jb3Jlb3MuY29tL3YxCmtpbmQ6IEFsZXJ0bWFuYWdlcgptZXRhZGF0YToKICBuYW1lOiBrcHMta3ViZS1wcm9tZXRoZXVzLXN0YWNrLWFsZXJ0bWFuYWdlciAgIyBVcGRhdGUgdGhpcyBuYW1lIHRvIG1hdGNoIHlvdXIgaW5zdGFsbGF0aW9uCiAgbmFtZXNwYWNlOiBtb25pdG9yaW5nCnNwZWM6CiAgcmVwbGljYXM6IDEKICBjb25maWdTZWNyZXQ6IGFsZXJ0bWFuYWdlci1tYWluCiAgY29uZmlnTWFwczogW10KICBzZWNyZXRzOiBbXQogIHBvZE1ldGFkYXRhOgogICAgbGFiZWxzOgogICAgICBhcHA6IGFsZXJ0bWFuYWdlcgogIHNlcnZpY2VBY2NvdW50TmFtZToga3BzLWt1YmUtcHJvbWV0aGV1cy1zdGFjay1hbGVydG1hbmFnZXIK
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
