version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api1
    depends_on:
      - postgresql
    ports:
      - "8081:3002"
    environment:
      DATABASE_URL: "postgresql://admin:password@postgres_db:5432/mydb?schema=public"

  api2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api2
    depends_on:
      - postgresql
    ports:
      - "8082:3002"
    environment:
      DATABASE_URL: "postgresql://admin:password@postgres_db:5432/mydb?schema=public"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

volumes:
  postgres_data:
