version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DATABASE_URL: "postgresql://admin:password@postgres_db:5432/mydb?schema=public"
    container_name: backend_app
    depends_on:
      - postgresql
    ports:
      - "3002:3002"
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://admin:password@postgres_db:5432/mydb?schema=public"

volumes:
  postgres_data:
