FROM node:20-alpine AS dev
WORKDIR /app  
RUN npm i -g pnpm nodemon ts-node
COPY package.json pnpm-lock.yaml ./ 
COPY prisma ./prisma 
RUN pnpm install --frozen-lockfile
COPY . .
ARG DATABASE_URL
ENV DATABASE_URL="postgresql://admin:password@localhost:5432/mydb?schema=public"
EXPOSE 3002
RUN pnpm dlx prisma@6.1.0 generate
CMD ["sh", "-c", "pnpm prisma migrate deploy && nodemon src/bin.ts"]

