apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: shubhamxshah/one2n-sre-prod:1.0.0
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: pg-secret
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: student-api
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: student-app
