apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rabbitmq
  namespace: default
spec:
  kvVersion: 1
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: k8s-role
  data:
    - name: RABBITMQ_USERNAME
      key: secret/Rabbitmq
      property: username
