apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: student-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-csi
