apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: default
spec:
  secretName: my-domain-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "shubhamxshah.xyz"
  dnsNames:
  - "shubhamxshah.xyz"
