---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # its a cluster wide resource so you can apply it anywhere. 
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: shubhamxshhwork@gmail.com 
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: shubhamxshahwork@gmail.com 
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "shubhamxshah.xyz"
