apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shubhamxshahwork@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: shubhamxshahwork@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret #comes from secret-cf-token.yaml which should be applied before.
              key: cloudflare-token
        selector:
          dnsZones:
            - "shubhamxshah.xyz"
