apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.service.name }} 
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.monitoring.release }} # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.service.name }}
  endpoints:
  - port: {{ .Values.app.service.portname }}
    path: /metrics
    interval: {{ .Values.monitoring.interval }}
