apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  selector:
    {{- include "student-app.labels" . | nindent 4 }}
