apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      {{- include "student-app.db.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "student-app.db.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.database.name }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          ports:
            - containerPort: {{ .Values.database.service.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_password
            - name: PGDATA
              value: {{ .Values.database.persistence.mountPath }}/{{ .Values.database.persistence.subPath }}
          volumeMounts:
            - mountPath: {{ .Values.database.persistence.mountPath }}
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: pg-pvc
