apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  selector:
    {{- include "student-app.db.labels" . | nindent 4 }}
