apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: {{ .Values.vault.version }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount }}
