apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-extsecret
  namespace: student-api
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: postgres_user
      remoteRef:
        key: postgrespw
        property: POSTGRES_USER
    - secretKey: postgres_password
      remoteRef:
        key: postgrespw
        property: POSTGRES_PASSWORD
    - secretKey: postgres_url
      remoteRef:
        key: postgrespw
        property: POSTGRES_URL
