promtail:
  config:
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
    logLevel: info
    serverPort: 3101
    snippets:    
      pipelineStages:
      - match:
          selector: '{namespace="student-api", app="student-app"}' # Ensure correct syntax
          stages:
            - json:  # Parse JSON logs if applicable
                expressions:
                  level: level
                  msg: message
            - labels:
                level: # Extract 'level' field as a log label
            - output:
                source: msg # Use 'msg' as the final log content
  enabled: true

loki:
  isDefault: false

