apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: express-app-alerts
  namespace: monitoring
spec:
  groups:
  - name: express.alerts
    rules:
    - alert: HighP90Latency
      expr: |
        histogram_quantile(0.90, 
          sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route)
        ) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High P90 latency on {{ $labels.route }}
        description: |
          90th percentile latency is above 500ms
          Route: {{ $labels.route }}
          Value: {{ printf "%.2f" $value }}s

    - alert: HighP99Latency
      expr: |
        histogram_quantile(0.99, 
          sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route)
        ) > 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: High P99 latency on {{ $labels.route }}
        description: |
          99th percentile latency is above 1s
          Route: {{ $labels.route }}
          Value: {{ printf "%.2f" $value }}s

    - alert: HighErrorRate
      expr: |
        sum(rate(http_request_duration_seconds_count{code=~"5.."}[5m])) by (route)
        /
        sum(rate(http_request_duration_seconds_count[5m])) by (route) * 100 > 5
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: High error rate on {{ $labels.route }}
        description: |
          Error rate is above 5%
          Route: {{ $labels.route }}
          Value: {{ printf "%.2f" $value }}%

    - alert: HighRequestRate
      expr: |
        sum(rate(http_request_duration_seconds_count[5m])) by (route) > 100
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High request rate on {{ $labels.route }}
        description: |
          Request rate is above 100 req/s
          Route: {{ $labels.route }}
          Value: {{ printf "%.2f" $value }} req/s
