---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificate
  namespace: student-api
spec:
  secretName: local-shubhamxshah-live-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.shubhamxshahwork@gmail.com"
  dnsNames:
  - "shubhamxshahwork@gmail.com"
  - "*.shubhamxshahwork@gmail.com"
