---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: one2n-prod-certificate
  namespace: student-api
spec:
  secretName: local-shubhamxshah-live-prod-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.shubhamxshah.xyz"
  dnsNames:
  - "shubhamxshah.xyz"
  - "*.shubhamxshah.xyz"
