name: Continuous Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: shubhamxshah/one2n-sre-prod:${{ github.sha }}

      - name: Clone staging-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Shubhamxshah/one2n-sre.git
          cd one2n-sre
          sed -i 's|apptag :.*|apptag :${{ github.sha }}|' helmchart/values.yml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add helmchart/values.yml
          git commit -m "Updated tag to ${{ github.sha }}"
          git push https://${PAT}@github.com/Shubhamxshah/one2n-sre.git main
